config/routes.rb
RailsMessagig::Application.routes.draw do
  root :to => 'pages#index'

   devise_for :admins, :controllers => { :sessions => "admins/sessions", :registrations =>  "admins/registrations"}
   namespace :admins do
    resources :dashboard
  end

  devise_for :users
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :timeoutable, :registerable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :remember_me, :name
  # attr_accessible :title, :body
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :role_id

  EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  validates :email,
            :uniqueness => true,
            :format => {:with => EMAIL_REGEX}

  validates_presence_of :name

  belongs_to :role

  has_attached_file :avatar,
                    :default_url => "/assets/default-avatar.gif",
                    :styles => {
                        :small => "120x120#",
                    }
  attr_accessible :email, :password, :password_confirmation, :remember_me
  acts_as_messageable
  def name
    email
  end

end

app/controllers/admins/application_controller.rb
# encoding: utf-8
require "application_responder"
class Admins::ApplicationController < ActionController::Base
  helper :all
  self.responder = ApplicationResponder
  respond_to :html, :json, :xml
  WillPaginate.per_page = 10

  before_filter :authenticate_admin!

  protect_from_forgery

end

app/controllers/admins/dashboard_controller.rb
class Admins::DashboardController < Admins::ApplicationController
  # To change this template use File | Settings | File Templates.
end

app/controllers/admins/registrations_controller.rb
class Admins::RegistrationsController < Devise::RegistrationsController
  def new
    redirect_to admins_dashboard_index_path
  end

  def create
    redirect_to admins_dashboard_index_path
  end

  def update
    super
  end
  protected

  def after_update_path_for(resource)
    admins_dashboard_index_path
  end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController

end

app/controllers/application_controller.rb
# encoding: utf-8
require "application_responder"
class ApplicationController < ActionController::Base
  helper :all
  self.responder = ApplicationResponder
  respond_to :html, :json, :xml
  WillPaginate.per_page = 10

  before_filter :authenticate_user!

  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "Yetkisiz erişim."
    redirect_to root_url
  end

  def after_sign_in_path_for(resource_or_scope)
    unless current_admin
      super
    else
      admins_dashboard_index_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    unless current_admin
      super
    else
      admins_dashboard_index_path
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!
  helper_method :mailbox, :conversation

  def create
    recipient_emails = conversation_params(:recipients).split(',')
    recipients = User.where(email: recipient_emails).all

    conversation = current_user.
        send_message(recipients, *conversation_params(:body, :subject)).conversation

    redirect_to conversation
  end

  def reply
    current_user.reply_to_conversation(conversation, *message_params(:body, :subject))
    redirect_to conversation
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to :conversations
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to :conversations
  end

  private

  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end

  def conversation_params(*keys)
    fetch_params(:conversation, *keys)
  end

  def message_params(*keys)
    fetch_params(:message, *keys)
  end

  def fetch_params(key, *subkeys)
    params[key].instance_eval do
      case subkeys.size
        when 0 then self
        when 1 then self[subkeys.first]
        else subkeys.map{|k| self[k] }
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_filter :authenticate_user!, :only => :index

  def index

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admins/dashboard/index.html.haml
%h1 Welcome to admin dashboard

app/views/conversations/_conversation.html.haml
= content_tag_for(:li, conversation) do |conversation|
  %p
    = link_to conversation.subject, conversation
    |
    - if conversation.is_completely_trashed?(current_user)
      = link_to 'Untrash', [:untrash, conversation], method: :post
    - else
      = link_to 'Move to trash', [:trash, conversation], method: :post

app/views/conversations/_form.html.haml
= simple_form_for :conversation, url: :conversations do |f|
  = f.input :recipients
  = f.input :subject
  = f.input :body
  .form-actions
    = f.button :submit, class: 'btn-primary'
    = submit_tag 'Cancel', type: :reset, class: 'btn btn-danger'

app/views/conversations/index.html.haml
%h1 Conversations
%h2 Inbox
%ul= render mailbox.inbox
%h2 Sentbox
%ul= render mailbox.sentbox
%h2 Trash
%ul= render mailbox.trash

= link_to 'Start Conversation', :new_conversation

app/views/conversations/new.html.haml
%h1 Start Conversation
= render 'form'

app/views/conversations/show.html.haml
%h1= conversation.subject
%ul
  = content_tag_for(:li, conversation.receipts_for(current_user)) do |receipt|
    - message = receipt.message
    %h3= message.subject
    %p= message.body
= render 'messages/form', conversation: conversation

app/views/layouts/admins/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title
      Rails Messagig | #{yield :title || "Hoşgeldiniz"}
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield :head
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.brand{:href => "/"}
          Rails Messagig
        .nav-collapse

          %ul.nav.pull-right
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                %i.icon-user.icon-white
                = current_admin.name
                %b.caret
              %ul.dropdown-menu
                %li= link_to t('nav.profile'), edit_admin_registration_path


    - if flash.count > 0
      .container
        .row-fluid
          - flash.each do |name, msg|
            %div{:class => "alert alert-#{name}"}
              %a.close{"data-dismiss" => "alert", :href => "#"} &times;
              = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
    .container
      .wrapper
        .wrap
          .head.row-fluid
            .span4.pull-left
              = yield :toolbar_left
            .span4.title
              %h2= yield :title
            .span4.pull-right
              = yield :toolbar_right
          = yield

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title
      Rails Messagig | #{yield :title || "Hoşgeldiniz"}
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield :head
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.brand{:href => "/"}
          Rails Messagig
        .nav-collapse

          %ul.nav.pull-right
            - if current_user
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  %i.icon-user.icon-white
                  = current_user.name
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to t('nav.profile'), edit_user_registration_path
                  %li.divider
                  %li= link_to t('nav.signout'), destroy_user_session_path, :method => :delete
            - else
              %li= link_to t('nav.signup'), new_user_registration_path
              %li= link_to t('nav.signin'), new_user_session_path


    - if flash.count > 0
      .container
        .row-fluid
          - flash.each do |name, msg|
            %div{:class => "alert alert-#{name}"}
              %a.close{"data-dismiss" => "alert", :href => "#"} &times;
              = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
    .container
      .wrapper
        .wrap
          .head.row-fluid
            .span4.pull-left
              = yield :toolbar_left
            .span4.title
              %h2= yield :title
            .span4.pull-right
              = yield :toolbar_right
          = yield

app/views/layouts/email.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    / Facebook sharing information tags
    %meta{:content => "*|MC:SUBJECT|*", :property => "og:title"}/
    %title *|MC:SUBJECT|*
    :css
      /* Client-specific Styles */
      #outlook a{padding:0;} /* Force Outlook to provide a "view in browser" button. */
      body{width:100% !important;} .ReadMsgBody{width:100%;} .ExternalClass{width:100%;} /* Force Hotmail to display emails at full width */
      body{-webkit-text-size-adjust:none;} /* Prevent Webkit platforms from changing default text sizes. */

      /* Reset Styles */
      body{margin:0; padding:0;}
      img{border:0; height:auto; line-height:100%; outline:none; text-decoration:none;}
      table td{border-collapse:collapse;}
      #backgroundTable{height:100% !important; margin:0; padding:0; width:100% !important;}

      /* Template Styles */

      /* /\/\/\/\/\/\/\/\/\/\ STANDARD STYLING: COMMON PAGE ELEMENTS /\/\/\/\/\/\/\/\/\/\ */

      /**
      * @tab Page
      * @section background color
      * @tip Set the background color for your email. You may want to choose one that matches your company's branding.
      * @theme page
      */
      body, #backgroundTable{
      	/*@editable*/ background-color:#FAFAFA;
      }

      /**
      * @tab Page
      * @section email border
      * @tip Set the border for your email.
      */
      #templateContainer{
      	/*@editable*/ border: 1px solid #DDDDDD;
      }

      /**
      * @tab Page
      * @section heading 1
      * @tip Set the styling for all first-level headings in your emails. These should be the largest of your headings.
      * @style heading 1
      */
      h1, .h1{
      	/*@editable*/ color:#202020;
      	display:block;
      	/*@editable*/ font-family:Arial;
      	/*@editable*/ font-size:34px;
      	/*@editable*/ font-weight:bold;
      	/*@editable*/ line-height:100%;
      	margin-top:0;
      	margin-right:0;
      	margin-bottom:10px;
      	margin-left:0;
      	/*@editable*/ text-align:left;
      }

      /**
      * @tab Page
      * @section heading 2
      * @tip Set the styling for all second-level headings in your emails.
      * @style heading 2
      */
      h2, .h2{
      	/*@editable*/ color:#202020;
      	display:block;
      	/*@editable*/ font-family:Arial;
      	/*@editable*/ font-size:30px;
      	/*@editable*/ font-weight:bold;
      	/*@editable*/ line-height:100%;
      	margin-top:0;
      	margin-right:0;
      	margin-bottom:10px;
      	margin-left:0;
      	/*@editable*/ text-align:left;
      }

      /**
      * @tab Page
      * @section heading 3
      * @tip Set the styling for all third-level headings in your emails.
      * @style heading 3
      */
      h3, .h3{
      	/*@editable*/ color:#202020;
      	display:block;
      	/*@editable*/ font-family:Arial;
      	/*@editable*/ font-size:26px;
      	/*@editable*/ font-weight:bold;
      	/*@editable*/ line-height:100%;
      	margin-top:0;
      	margin-right:0;
      	margin-bottom:10px;
      	margin-left:0;
      	/*@editable*/ text-align:left;
      }

      /**
      * @tab Page
      * @section heading 4
      * @tip Set the styling for all fourth-level headings in your emails. These should be the smallest of your headings.
      * @style heading 4
      */
      h4, .h4{
      	/*@editable*/ color:#202020;
      	display:block;
      	/*@editable*/ font-family:Arial;
      	/*@editable*/ font-size:22px;
      	/*@editable*/ font-weight:bold;
      	/*@editable*/ line-height:100%;
      	margin-top:0;
      	margin-right:0;
      	margin-bottom:10px;
      	margin-left:0;
      	/*@editable*/ text-align:left;
      }

      /* /\/\/\/\/\/\/\/\/\/\ STANDARD STYLING: PREHEADER /\/\/\/\/\/\/\/\/\/\ */

      /**
      * @tab Header
      * @section preheader style
      * @tip Set the background color for your email's preheader area.
      * @theme page
      */
      #templatePreheader{
      	/*@editable*/ background-color:#FAFAFA;
      }

      /**
      * @tab Header
      * @section preheader text
      * @tip Set the styling for your email's preheader text. Choose a size and color that is easy to read.
      */
      .preheaderContent div{
      	/*@editable*/ color:#505050;
      	/*@editable*/ font-family:Arial;
      	/*@editable*/ font-size:10px;
      	/*@editable*/ line-height:100%;
      	/*@editable*/ text-align:left;
      }

      /**
      * @tab Header
      * @section preheader link
      * @tip Set the styling for your email's preheader links. Choose a color that helps them stand out from your text.
      */
      .preheaderContent div a:link, .preheaderContent div a:visited, /* Yahoo! Mail Override */ .preheaderContent div a .yshortcuts /* Yahoo! Mail Override */{
      	/*@editable*/ color:#336699;
      	/*@editable*/ font-weight:normal;
      	/*@editable*/ text-decoration:underline;
      }

      /* /\/\/\/\/\/\/\/\/\/\ STANDARD STYLING: HEADER /\/\/\/\/\/\/\/\/\/\ */

      /**
      * @tab Header
      * @section header style
      * @tip Set the background color and border for your email's header area.
      * @theme header
      */
      #templateHeader{
      	/*@editable*/ background-color:#FFFFFF;
      	/*@editable*/ border-bottom:0;
      }

      /**
      * @tab Header
      * @section header text
      * @tip Set the styling for your email's header text. Choose a size and color that is easy to read.
      */
      .headerContent{
      	/*@editable*/ color:#202020;
      	/*@editable*/ font-family:Arial;
      	/*@editable*/ font-size:34px;
      	/*@editable*/ font-weight:bold;
      	/*@editable*/ line-height:100%;
      	/*@editable*/ padding:0;
      	/*@editable*/ text-align:center;
      	/*@editable*/ vertical-align:middle;
      }

      /**
      * @tab Header
      * @section header link
      * @tip Set the styling for your email's header links. Choose a color that helps them stand out from your text.
      */
      .headerContent a:link, .headerContent a:visited, /* Yahoo! Mail Override */ .headerContent a .yshortcuts /* Yahoo! Mail Override */{
      	/*@editable*/ color:#336699;
      	/*@editable*/ font-weight:normal;
      	/*@editable*/ text-decoration:underline;
      }

      #headerImage{
      	height:auto;
      	max-width:600px !important;
      }

      /* /\/\/\/\/\/\/\/\/\/\ STANDARD STYLING: MAIN BODY /\/\/\/\/\/\/\/\/\/\ */

      /**
      * @tab Body
      * @section body style
      * @tip Set the background color for your email's body area.
      */
      #templateContainer, .bodyContent{
      	/*@editable*/ background-color:#FFFFFF;
      }

      /**
      * @tab Body
      * @section body text
      * @tip Set the styling for your email's main content text. Choose a size and color that is easy to read.
      * @theme main
      */
      .bodyContent div{
      	/*@editable*/ color:#505050;
      	/*@editable*/ font-family:Arial;
      	/*@editable*/ font-size:14px;
      	/*@editable*/ line-height:150%;
      	/*@editable*/ text-align:left;
      }

      /**
      * @tab Body
      * @section body link
      * @tip Set the styling for your email's main content links. Choose a color that helps them stand out from your text.
      */
      .bodyContent div a:link, .bodyContent div a:visited, /* Yahoo! Mail Override */ .bodyContent div a .yshortcuts /* Yahoo! Mail Override */{
      	/*@editable*/ color:#336699;
      	/*@editable*/ font-weight:normal;
      	/*@editable*/ text-decoration:underline;
      }

      .bodyContent img{
      	display:inline;
      	height:auto;
      }

      /* /\/\/\/\/\/\/\/\/\/\ STANDARD STYLING: FOOTER /\/\/\/\/\/\/\/\/\/\ */

      /**
      * @tab Footer
      * @section footer style
      * @tip Set the background color and top border for your email's footer area.
      * @theme footer
      */
      #templateFooter{
      	/*@editable*/ background-color:#FFFFFF;
      	/*@editable*/ border-top:0;
      }

      /**
      * @tab Footer
      * @section footer text
      * @tip Set the styling for your email's footer text. Choose a size and color that is easy to read.
      * @theme footer
      */
      .footerContent div{
      	/*@editable*/ color:#707070;
      	/*@editable*/ font-family:Arial;
      	/*@editable*/ font-size:12px;
      	/*@editable*/ line-height:125%;
      	/*@editable*/ text-align:left;
      }

      /**
      * @tab Footer
      * @section footer link
      * @tip Set the styling for your email's footer links. Choose a color that helps them stand out from your text.
      */
      .footerContent div a:link, .footerContent div a:visited, /* Yahoo! Mail Override */ .footerContent div a .yshortcuts /* Yahoo! Mail Override */{
      	/*@editable*/ color:#336699;
      	/*@editable*/ font-weight:normal;
      	/*@editable*/ text-decoration:underline;
      }

      .footerContent img{
      	display:inline;
      }

      /**
      * @tab Footer
      * @section social bar style
      * @tip Set the background color and border for your email's footer social bar.
      * @theme footer
      */
      #social{
      	/*@editable*/ background-color:#FAFAFA;
      	/*@editable*/ border:0;
      }

      /**
      * @tab Footer
      * @section social bar style
      * @tip Set the background color and border for your email's footer social bar.
      */
      #social div{
      	/*@editable*/ text-align:center;
      }

      /**
      * @tab Footer
      * @section utility bar style
      * @tip Set the background color and border for your email's footer utility bar.
      * @theme footer
      */
      #utility{
      	/*@editable*/ background-color:#FFFFFF;
      	/*@editable*/ border:0;
      }

      /**
      * @tab Footer
      * @section utility bar style
      * @tip Set the background color and border for your email's footer utility bar.
      */
      #utility div{
      	/*@editable*/ text-align:center;
      }

      #monkeyRewards img{
      	max-width:190px;
      }
  %body{:leftmargin => "0", :marginheight => "0", :marginwidth => "0", :offset => "0", :topmargin => "0"}
    %center
      %table#backgroundTable{:border => "0", :cellpadding => "0", :cellspacing => "0", :height => "100%", :width => "100%"}
        %tr
          %td{:align => "center", :valign => "top"}

            %table#templateContainer{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "600"}
              %tr
                %td{:align => "center", :valign => "top"}
                  / // Begin Template Header \\
                  %table#templateHeader{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "600"}
                    %tr
                      %td.headerContent
                        / // Begin Module: Standard Header Image \\
                        %img{:id => "headerImage campaign-icon", "mc:allowdesigner" => "", "mc:allowtext" => "", "mc:edit" => "header_image", "mc:label" => "header_image", :src => "#{root_url}/assets/header.png", :style => "max-width:600px;"}/
                        / // End Module: Standard Header Image \\
                  / // End Template Header \\
              %tr
                %td{:align => "center", :valign => "top"}
                  / // Begin Template Body \\
                  %table#templateBody{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "600"}
                    %tr
                      %td.bodyContent{:valign => "top"}
                        / // Begin Module: Standard Content \\
                        %table{:border => "0", :cellpadding => "20", :cellspacing => "0", :width => "100%"}
                          %tr
                            %td{:valign => "top"}
                              %div{"mc:edit" => "std_content00"}
                                = yield
                        / // End Module: Standard Content \\
                  / // End Template Body \\
              %tr
                %td{:align => "center", :valign => "top"}
                  / // Begin Template Footer \\
                  %table#templateFooter{:border => "0", :cellpadding => "10", :cellspacing => "0", :width => "600"}
                    %tr
                      %td.footerContent{:valign => "top"}
                        / // Begin Module: Standard Footer \\
                        %table{:border => "0", :cellpadding => "10", :cellspacing => "0", :width => "100%"}
                          %tr
                            %td#utility{:colspan => "2", :valign => "middle"}
                              %div{"mc:edit" => "std_utility"}
                                %a{:href => "http://www.lab2023.com"} lab2023.com


                        / // End Module: Standard Footer \\
                  / // End Template Footer \\
            %br/

app/views/messages/_form.html.haml
= simple_form_for :message, url: [:reply, conversation] do |f|
  = f.input :subject
  = f.input :body
  .form-actions
    = f.button :submit, class: 'btn-primary'
    = submit_tag 'Cancel', type: :reset, class: 'btn btn-danger'

app/views/pages/index.html.haml
%h1 Welcome to lab2023 – internet technologies